exports.paginaInicial = function(d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores e Períodos da Música</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-khaki">
                    <h1>Compositores e Períodos da Música</h1>
                </header>
        
                <div class="w3-container">
                    <ul>
                        <li><a href="/compositores">Compositores</a></li>
                        <li><a href="/periodos">Periodos</a></li>
                    </ul>
                </div>
                <footer class="w3-container w3-khaki">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
}

// ---------------Compositores----------------------------------

exports.compositoresListPage = function(compositores, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Lista de Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-khaki">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-black" href="/compositores/criar">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>ID</th><th>Nome</th><th>Actions</th>
                        </tr>
                `
    for(let i=0; i < compositores.length ; i++){
        pagHTML += `
                <tr>
                    <td>${compositores[i].id}</td>
                    <td>
                        <a href="/compositores/${compositores[i].id}">
                            ${compositores[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/compositores/edit/${compositores[i].id}">Editar</a>][<a href="/compositores/delete/${compositores[i].id}">Apagar Compositor</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-khaki">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Voltar à página inicial</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.compositorPage = function(compositor, d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>${compositor.nome}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-khaki">
                    <h1>${compositor.nome}</h1>
                </header>
        
                <div class="w3-container">
                    <p>ID: ${compositor.id}</p>
                    <p>Nome: ${compositor.nome}</p>
                    <p>Biografia: ${compositor.bio}</p>
                    <p>Data de nascimento: ${compositor.dataNasc}</p>
                    <p>Data de obito: ${compositor.dataObito}</p>
                    <p>Periodo: ${compositor.periodo}</p>
                </div>
                <footer class="w3-container w3-khaki">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Voltar aos compositores</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
}

exports.compositorFormPage = function(periodos, d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="./extras/w3.css"/>
            <title>Adicionar Compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-khaki">
                    <h2>Adicionar Compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                <fieldset>
                    <legend>Metadata</legend>
                    <label>ID</label>
                    <input class="w3-input w3-round" type="text" name="id"/>
                    <label>Nome</label>
                    <input class="w3-input w3-round" type="text" name="nome"/>
                    <label>Data de Nascimento</label>
                    <input class="w3-input w3-round" type="text" name="dataNasc"/>
                    <label>Data de Óbito</label>
                    <input class="w3-input w3-round" type="text" name="dataObito"/>
                    <label>Período</label>
                    <select class="w3-input w3-round" name="periodo">
                    ${periodos.map(periodo => `<option value="${periodo.nome}">${periodo.nome}</option>`).join('')}</select>
                    <label>Bio</label>
                    <input class="w3-input w3-round" type="text" name="bio"/>
                </fieldset>

                    
                    <br/>
                    <button class="w3-btn w3-black w3-mb-2" type="submit">Criar</button>

                </form>
                <br/>
                <footer class="w3-container w3-khaki">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/compositores">Voltar aos compositores</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.compositorFormEditPage = function(compositor, periodos, d){
        var pagHTML = `
        <!DOCTYPE html>
        <html>
            <head>
                <meta charset="UTF-8"/>
                <link rel="icon" href="favicon.png"/>
                <link rel="stylesheet" href="w3.css"/>
                <title>${compositor.nome}</title>
            </head>
            <body>
                <div class="w3-card-4">
                    <header class="w3-container w3-khaki">
                        <h2>${compositor.nome}</h2>
                    </header>
                
                    <form class="w3-container" method="POST">
                        <fieldset>
                            <legend>Metadata</legend>
                            <label>ID</label>
                            <input class="w3-input w3-round" type="text" name="id" readonly value="${compositor.id}"/>
                            <label>Nome</label>
                            <input class="w3-input w3-round" type="text" name="nome" value="${compositor.nome}"/>
                            <label>Data de Nascimento</label>
                            <input class="w3-input w3-round" type="text" name="dataNasc" value="${compositor.dataNasc}"/>
                            <label>Data de Óbito</label>
                            <input class="w3-input w3-round" type="text" name="dataObito" value="${compositor.dataObito}"/>
                            <label>Período</label>
                            <select class="w3-input w3-round" name="periodo">
                            ${periodos.map(periodo => `<option value="${periodo.nome}">${periodo.nome}</option>`).join('')}</select>
                            <label>Bio</label>
                            <input class="w3-input w3-round" type="text" name="bio" value="${compositor.bio}"/>
                        </fieldset>
                        <br/>
                        <button class="w3-btn w3-black w3-mb-2" type="submit">Editar</button>
                    </form>
                    <br/>
                    <footer class="w3-container w3-khaki">
                        <h5>Generated by EngWeb2023 in ${d} - [<a href="/compositores">Voltar aos compositores</a>]</h5>
                    </footer>
                
                </div>
        `
        return pagHTML
    }

// ---------------Períodos--------------------------------

exports.periodosListPage = function(periodos, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Lista de Períodos</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-khaki">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-black" href="/periodos/criar">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>ID</th><th>Nome</th><th>Actions</th>
                        </tr>
                `
    for(let i=0; i < periodos.length ; i++){
        pagHTML += `
                <tr>
                    <td>${periodos[i].id}</td>
                    <td>
                        <a href="/periodos/${periodos[i].id}">
                            ${periodos[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${periodos[i].id}">Editar</a>][<a href="/periodos/delete/${periodos[i].id}">Apagar Período</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-khaki">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Voltar à página inicial</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodoPage = (periodo,compositores,d) => {
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel ="stylesheet" href="./extras/w3.css"/>
        <title>${periodo.nome}</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class = "w3-container w3-khaki">
                <h1>${periodo.nome}</h1>
            </header>
            <div class="w3-container">`
            for(let i = 0; i < compositores.length; i++){
                if(compositores[i].periodo == periodo.id)
                    pagHTML += `<a href="/compositores/${compositores[i].id}"><p>${compositores[i].nome}</p></a>`
            }
            
        pagHTML += `
            </div>
            <br>
        <footer class="w3-container w3-khaki">
            <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Voltar aos períodos</a>]</h5>
        </footer>
        </div>


    </body>
    </html>
    `
    return pagHTML
}
    

exports.periodoFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Adicionar Período</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-khaki">
                    <h2>Adicionar Período</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>ID</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    </fieldset>
                    
                    <br/>
                    <button class="w3-btn w3-khaki w3-mb-2" type="submit">Registar</button>
                </form>

                <footer class="w3-container w3-khaki">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Voltar aos períodos</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.periodoFormEditPage = function(periodo, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar Período</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Editar Período</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>ID</label>
                        <input class="w3-input w3-round" type="text" name="id" value="${periodo.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${periodo.nome}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-khaki w3-mb-2" type="submit">Registar</button>
                </form>

                <footer class="w3-container w3-khaki">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Voltar aos períodos</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// --------------Errors-----------------------------------

exports.errorPage = function(errorMessage, d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Página de Erro</title>
        </head>
        <body>
            <div class="w3-card-4">
                <div class="w3-container">
                    <p>${d}: Erro ocorrido: ${errorMessage}</p>
                </div>

                <footer class="w3-container w3-khaki">
                    <address><h5>Generated by EngWeb2024 in ${d} - [<a href="/">Voltar à página inicial</a>]</h5></address>
                </footer>
            </div>
        </body>
    </html>
    `
}